### ISSUE TITLE
Questions about the library

### ISSUE THREAD

**Issue by adaojunior** [matthewfranglen/dart-jsonp#2]
Hi, I'm working in an application sample that will be used in the [angular.io](https://angular.io/docs/dart/latest/guide/) website and I may use your library but since we will be encouraging people to use this library, I have some concerns/questions.
- When I built the app, the compiler said it uses mirrors and generated a 3.6 mb file when it should be around 500 kb, is there a way to solve this?
- Does it make sense to upgrade part of the `dart:js` to the new `package:js` [link](https://pub.dartlang.org/packages/js) ?

> This library is not required because you can make JSONP requests very easily with pure Dart. This library does reduce the work required to make JSONP requests.
- Seems like you don't encourage people to use this library but I asked some people in the community and I could not find something as easy as your library to handle JSONP requests.
- Would you be willing to remove the Polymer dependency to avoid possible package version conflicts (I could help with that) ?

That's it for now, thank you

**Comment by adaojunior** [comment]
Inspired by your comment on the readme I created this experiment [adaojunior/jsonp](https://github.com/adaojunior/jsonp).

**Comment by matthewfranglen** [comment]
Thanks for the comments. I will address them properly tonight. I just wanted to cover this statement:

> This library is not required because you can make JSONP requests very easily with pure Dart. This library does reduce the work required to make JSONP requests.

When I initially wrote the library the javascript interop available was very onerous. You had to do things like [explicitly retaining the returned json data](https://github.com/matthewfranglen/dart-jsonp/blob/d05745a9d26b61c78cf14d05573a59afff286140/lib/jsonp.dart#L44) and [explicitly disposing of the JsCallback](https://github.com/matthewfranglen/dart-jsonp/blob/d05745a9d26b61c78cf14d05573a59afff286140/lib/jsonp.dart#L156). That situation was improved some time ago, which was when I wrote that comment. Based on your experience it seems I overstated the ease with which you can do it in pure dart.

**Comment by matthewfranglen** [comment]
> When I built the app, the compiler said it uses mirrors and generated a 3.6 mb file when it should be around 500 kb, is there a way to solve this?

This is because of the [transformation into the target type](https://github.com/matthewfranglen/dart-jsonp#type-conversion). That compiler warning was unsolveable before as there was no documentation on how to actually satisfy it. If you follow the link that is in that error message you arrive here: https://github.com/dart-lang/sdk/issues/21654 which has no links to any actual information on how to satisfy the compiler.

Documentation on the @MirrorsUsed annotation has turned up but I am unable to discover the correct way to use it. Adding the literal example that they provide in the [now available documentation](https://api.dartlang.org/1.13.2/dart-mirrors/MirrorsUsed-class.html) _does not stop the compiler from moaning_.

> Would you be willing to remove the Polymer dependency to avoid possible package version conflicts (I could help with that) ?

The polymer dependency is a dev dependency so it should not interfere with your code? As [documented here](https://www.dartlang.org/tools/pub/dependencies.html#dev-dependencies) dev dependencies are only used when the library is the current thing you are working on. When you merely depend on the library dev dependencies are ignored.

**Comment by matthewfranglen** [comment]
I have just looked at your example. It seems pretty good. My notes are:
- Your implementation is (clearly) intended to be synchronous. You may run into trouble with jsonp calls that fail, as they will never trigger the callback
- Your implementation is synchronous so maybe you should just return the value rather than the future
- You may want to release the callback function by clearing the entry in the context after the completion of the jsonp call

Anyway your quick implementation kinda vindicates my comment regarding it being easy. You can boil your implementation down to:

``` dart
import 'dart:html';
import 'dart:js';
import 'dart:async';

Future<dynamic> call() {
    var uri = "http://some.service/?callback=jsonp_callback";
    Completer result = new Completer();

    context['jsonp_callback'] = (data) {
        result.complete(data);
        // could type convert here without invoking the wrath of mirrors

        context['jsonp_callback'] = null;
    };
    document.body.append(
        new ScriptElement()
            ..src = uri
    );

    return result.future;
}
```

**Comment by matthewfranglen** [comment]
And yeah, that example is very concrete and specific. However it would work and as such this library can be replaced by ~10 lines of code. Also the attempt to support nice type conversion makes this library painful to use. Without the type conversion there is almost no substance to this library.

The next step would be to remove the type conversion, as that would then make the resulting use of this library much smaller. I guess I just kinda like the reflection capabilities of dart and I have found it very hard to let that go, even though the implementation of them has been both poor and incomplete for dart2js since I started.

**Comment by matthewfranglen** [comment]
On the `package:js` stuff, I see no real benefit that that would provide. This is mainly because the callback function is named unpredictably and as such cannot be annotated.

**Comment by matthewfranglen** [comment]
So yeah I can remove the mirror code and that would cut the size. If you can explain why the polymer dependency is so bad then I'll certainly consider removing that too. I might as well add the code that would be equivalent to the readme so that people can judge for themselves what is easier.

**Comment by matthewfranglen** [comment]
I probably sound very negative. I realise that. I do appreciate the fact that you are evaluating this library for inclusion in your website.

**Comment by matthewfranglen** [comment]
And now I see that I did write a section on the equivalent dart code. Good job me :wink:

Needs a clean though.

**Comment by matthewfranglen** [comment]
Pushed some changes. See what you think. I haven't created a new version yet as this breaks backwards compatibility.

**Comment by adaojunior** [comment]
Thanks for your efforts, I'll be looking into it tomorrow.

**Comment by bw-matthew** [comment]
Make sure you look at the develop branch. It would probably just be best to review this commit:

https://github.com/matthewfranglen/dart-jsonp/commit/12e591366e04cf8a0209f5cebe2f1225ed3f13ee

And then read the updated README:

https://github.com/matthewfranglen/dart-jsonp/tree/develop

**Comment by adaojunior** [comment]
I don't really have a good point to remove polymer since it is a dev_dependency, I said that because I had run into problems because of it before (you already fixed).
Also, I updated my experiment [adaojunior/jsonp](https://github.com/adaojunior/jsonp), now it removes the callback reference and also handles some errors.
Also, do you think `uriGenerator` is still necessary ?
Seems like you could solve that like this https://github.com/adaojunior/jsonp/blob/master/lib/src/jsonp_call.dart#L46-L51
About your implementation, it seems fine now, I just don't understand why it has way more code than mine (even thought you handle Streams).

**Comment by matthewfranglen** [comment]
My code is way bigger because it is overdue for a refactor. It was also split up to allow the core functionality to be tested without requiring a browser. I'm not sure what has changed with dart testing because the fairly simple tests that were written for it no longer work. Unfortunately my enduring experience with dart has been that working code breaks over time.

When the change occurred that simplified the use of javascript from dart I did the minimum required to make the library compatible. I should properly address this now as it will require a change in the external API.

The url generator is still required because JSONP does not have a fixed callback query parameter. While the `callback` parameter is often used, it is not the only parameter that is used.

**Comment by adaojunior** [comment]
Do you think we could use my experiment as a new version of this package ?
I made some changes to fix the problems you pointed out. I only need some testing and a proper use case example.
I published it to pub and I can add you as a collaborator (if you want) since you gave me valuable feedback.

**Comment by matthewfranglen** [comment]
I'm not keen on using your experiment as the next version because it changes the api, it has less documentation, and it lacks support for repeated requests.

Since the problem with my code is the size and the dependency, I have updated it. The new version does not use mirrors, so the generated code is small. I have taken this opportunity to refactor it, so the library itself is smaller. It also does not have any dependencies, so there is no chance of a conflict. It still supports the complex url generation, but all you have to do is use a URL with a ? placeholder, like:

http://en.wikipedia.org/w/api.php?search=brazil&action=opensearch&format=json&callback=?

The example code I have written does use the wikipedia jsonp endpoint from your own example. Thanks for finding that.

I hope these changes address all of your problems. If you want to stick with your library then perhaps you should consider the name `ng-jsonp` or similar since you are going to use it on an angular website. You may also want to populate a ng-model (or whatever the dart equivalent is) based on the result of the jsonp call rather than using a future. Just a thought.

**Comment by matthewfranglen** [comment]
If this concludes this issue then please close this ticket. Any further discussion about the library is welcome.

**Comment by adaojunior** [comment]
Ok, thanks for all the feedback.
